version: '3'

services:
  postgres:
    image: postgres:13.2
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"

  dos_auth:
    build:
      context: .
    image: democracyos/auth:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres:postgres
